# Generated by Django 2.2.16 on 2023-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230202_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
